### ISSUE TITLE
Release a 1.0.0 version

### ISSUE THREAD

**Issue by artob** [brianegan/transparent_image#3]
As there is a significant Flutter package ([flutter_map](https://pub.dartlang.org/packages/flutter_map)) that [depends](https://pub.dartlang.org/packages?q=dependency%3Atransparent_image) on this package, and that means this package is in fact getting deployed in production environments, I would suggest that the current 0.1.0 might as well get renamed to a proper 1.0.0?

**Comment by mayurdhurpate** [comment]
True, flutter uses this package in their fade in cookbook example too: https://flutter.dev/docs/cookbook/images/fading-in-images#in-memory

Would be great if we could improve the documentation a bit.

**Comment by brianegan** [comment]
Hey, sorry I missed this!

Haha, sounds good. I'll add some simple docs and make it 1.0.0

**Comment by brianegan** [comment]
Boom. Done. https://pub.dartlang.org/packages/transparent_image

**Comment by artob** [comment]
Great, thanks!
