### ISSUE TITLE
How to get kTransparentImage as an ImageProvider

### ISSUE THREAD

**Issue by MichaelFerrier** [brianegan/transparent_image#4]
I'm looking to use FadeInImage with the NetworkImageWithRetry class (to fix the occasional image that fails to load on the first try).  To do this I will need to use the FadeInImage constructor that takes an ImageProvider for both the image and the placeholder. kTransparentImage won't work with that FadeInImage constructor because its type is Uint8List rather than ImageProvider. So I'm wondering if there's any way to access the kTransparentImage as an ImageProvider, or if such a way could be added? Thank you!

**Comment by brianegan** [comment]
Hey there -- I just added some instructions to the README! Please let me know if that works out for ya :)

**Comment by MichaelFerrier** [comment]
Perfect -- thank you!
