### ISSUE TITLE
Asset image

### ISSUE THREAD

**Issue by erperejildo** [brianegan/transparent_image#6]
How can I use this package for assets on the phone? Sometimes I need to display big images and I need a spinner for them.

**Comment by MostHated** [comment]
What I was about to try was this:

Using a placeholder default if the image isn't found (news[0].image would just be replaced with the link to the image you want)
```dart
child: (news[0].image == null)
  ? AssetImage('assets/images/searcher_default.png')
  : FadeInImage.memoryNetwork(
      placeholderCacheHeight: 180,
      placeholder: kTransparentImage,
      image: '${news[0].image}',
      fit: BoxFit.fitWidth,
    )),
```
You could just do that, but replace the AssetImage with : Center(child: CircularProgressIndicator())

```dart
child: (news[0].image == null)
  ? Center(child: CircularProgressIndicator())
  : FadeInImage.memoryNetwork(
      placeholderCacheHeight: 180,
      placeholder: kTransparentImage,
      image: '${news[0].image}',
      fit: BoxFit.fitWidth,
    )),
```

Thanks, 
-MH
